# ID предмета который будет паспортом
item: 340

# Имя предмета который будет паспортом
item-name: "§l§c[§6Паспорт§c]"

# Если стоит true, то при показе паспорта он будет забран. Это было сделано чтоб игроки не спамили в чат. false - чтоб отключить изятие предмета
item-remove: true

# Вывод сообщения при нажатии паспортом
text: "§l§f| §6Игрок §b{name} §6показал паспорт\n§l§f| §eПривилегия: §3{group}\n§l§f| §eДенег: §2{money}$\n§l§f| §eПоставлено блоков: §c{placed}\n§l§f| §eСломано блоков: §c{breaked}\n§l§f| §eУбийств: §c{kills}\n§l§f| §eСмертей: §c{deaths}"

# Сообщение если вы не в игре
no-permission-command: "§l§c> §eУ Вас не прав чтоб использовать эту команду"

# Сообщение если нет прав на предмет
no-permission-item: "§l§c> §eВы не можете показать паспорт всем ибо у Вас нет прав"

# Сообщения если нет прав на команду
command-no-console: "§l§c> §eКоманду можно использовать только в игре"

# Сообщения о выдаче паспорта
add-passport: "§l§c> §aВам успешно был выдан паспорт"